# https://adventofcode.com/2023/day/11

""" *** Puzzle 1 ***

The researcher has collected a bunch of data and compiled the data into a single giant image (your puzzle input).
The image includes empty space (.) and galaxies (#). For example:

...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....
The researcher is trying to figure out the sum of the lengths of the shortest path between every pair of galaxies.
However, there's a catch: the universe expanded in the time it took the light from those galaxies to reach the
observatory.

Due to something involving gravitational effects, only some space expands. In fact, the result is that any rows or

columns that contain no galaxies should all actually be twice as big.

In the above example, three columns and two rows contain no galaxies:

   v  v  v
 ...#......
 .......#..
 #.........
>..........<
 ......#...
 .#........
 .........#
>..........<
 .......#..
 #...#.....
   ^  ^  ^
These rows and columns need to be twice as big; the result of cosmic expansion therefore looks like this:

....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......
Equipped with this expanded universe, the shortest path between every pair of galaxies can be found. It can help to
assign every galaxy a unique number:

....1........
.........2...
3............
.............
.............
........4....
.5...........
............6
.............
.............
.........7...
8....9.......
In these 9 galaxies, there are 36 pairs. Only count each pair once; order within the pair doesn't matter. For each pair,
find any shortest path between the two galaxies using only steps that move up, down, left, or right exactly one .
or # at a time. (The shortest path between two galaxies is allowed to pass through another galaxy.)

For example, here is one of the shortest paths between galaxies 5 and 9:

....1........
.........2...
3............
.............
.............
........4....
.5...........
.##.........6
..##.........
...##........
....##...7...
8....9.......
This path has length 9 because it takes a minimum of nine steps to get from galaxy 5 to galaxy 9 (the eight locations
marked # plus the step onto galaxy 9 itself). Here are some other example shortest path lengths:

Between galaxy 1 and galaxy 7: 15
Between galaxy 3 and galaxy 6: 17
Between galaxy 8 and galaxy 9: 5
In this example, after expanding the universe, the sum of the shortest path between all 36 pairs of galaxies is 374.

Expand the universe, then find the length of the shortest path between every pair of galaxies. What is the sum of these
lengths?
"""

universe = [[x for x in line.strip()] for line in open('input/day_11.txt').readlines()]

for i in range(len(universe)-1, -1, -1):
    if '#' not in universe[i]:
        universe.insert(i+1, [x for x in universe[i]])
for j in range(len(universe[0])-1, -1, -1):
    if '#' not in [universe[x][j] for x in range(0, len(universe))]:
        for i in range(0, len(universe)):
            universe[i].insert(j+1, '.')

galaxies = [[i, j] for i in range(0, len(universe)) for j in range(0, len(universe[i])) if universe[i][j] == '#']
distances = [abs(galaxies[i][0] - galaxies[j][0]) + abs(galaxies[i][1] - galaxies[j][1])
             for i in range(0, len(galaxies)-1) for j in range(i+1, len(galaxies))]

print("Solution for Puzzle 1: {}".format(sum(distances)))


""" *** Puzzle 2 ***

The galaxies are much older (and thus much farther apart) than the researcher initially estimated.

Now, instead of the expansion you did before, make each empty row or column one million times larger. That is, each 
empty row should be replaced with 1000000 empty rows, and each empty column should be replaced with 1000000 empty 
columns.

(In the example above, if each empty row or column were merely 10 times larger, the sum of the shortest paths between 
every pair of galaxies would be 1030. If each empty row or column were merely 100 times larger, the sum of the shortest 
paths between every pair of galaxies would be 8410. However, your universe will need to expand far beyond these values.)

Starting with the same initial image, expand the universe according to these new rules, then find the length of the 
shortest path between every pair of galaxies. What is the sum of these lengths?
"""

universe = [[x for x in line.strip()] for line in open('input/day_11.txt').readlines()]
rows_to_be_expanded = [i for i in range(len(universe)-1, -1, -1) if '#' not in universe[i]]
cols_to_be_expanded = [j for j in range(len(universe[0])-1, -1, -1)
                       if '#' not in [universe[x][j] for x in range(0, len(universe))]]
galaxies = [[i, j] for i in range(0, len(universe)) for j in range(0, len(universe[i])) if universe[i][j] == '#']

distances = [abs(galaxies[i][0] - galaxies[j][0]) + abs(galaxies[i][1] - galaxies[j][1]) +
             sum([1 for r in rows_to_be_expanded
                  if galaxies[i][0] < r < galaxies[j][0] or galaxies[i][0] > r > galaxies[j][0]]) * 999999 +
             sum([1 for c in cols_to_be_expanded
                  if galaxies[i][1] < c < galaxies[j][1] or galaxies[i][1] > c > galaxies[j][1]]) * 999999
             for i in range(0, len(galaxies)-1) for j in range(i+1, len(galaxies))]

print("Solution for Puzzle 2: {}".format(sum(distances)))
